steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=elasticsearch-operator']
- name: 'gcr.io/cloud-builder/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/elasticsearch-operator', '.']
images: ['gcr.io/$PROJECT_ID/elasticsearch-operator']
