steps:
- name: 'gcr.io/$PROJECT_ID/cloud-builders/go-elasticsearch-operator'
  args: ['get', 'github.com/matt-tyler/elasticsearch-operator']
  env: 
    - 'GOPATH=/workspace/gopath'
    - 'CGO_ENABLED=0'
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - build
    - '--tag=gcr.io/$PROJECT_ID/elasticsearch-operator'
    - '--file=Dockerfile.cloudbuild'
    - '.'
images: ['gcr.io/$PROJECT_ID/elasticsearch-operator']
