FROM gcr.io/cloud-builders/go:alpine

RUN mkdir -p /scratch/src/github.com/matt-tyler && mkdir /workspace

RUN GOPATH=/scratch go get -u github.com/golang/dep/cmd/dep

WORKDIR /scratch/src/github.com/matt-tyler

RUN git clone https://github.com/matt-tyler/elasticsearch-operator \ 
 && cd elasticsearch-operator \
 && GOPATH=/scratch /scratch/bin/dep ensure \
 && mv /scratch/src/github.com/matt-tyler/elasticsearch-operator/vendor /workspace/vendor

